notifications:
 email:
  recipients:
   - pk.roger@icloud.com
                           
before_install:
 - sudo sed -i -e '$adeb http://cran.univ-paris1.fr/bin/linux/ubuntu trusty/' /etc/apt/sources.list
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
 - sudo apt-get update
 - sudo apt-get install -y r-base
 - sudo R -e "install.packages(c('getopt', 'stringr', 'plyr', 'XML', 'jsonlite', 'bitops', 'stats', 'R.utils', 'digest', 'testthat', 'devtools'), lib='/usr/lib/R/library', dependencies = TRUE, repos='http://cran.univ-paris1.fr/')"

branches:
  only:
    - master
    - develop
 
script:
 - make test
 - make install
 - make test-examples
